"""Repository interfaces (Protocols) for RedForge persistence.

These are the ONLY persistence contracts the core depends on. Each repository
manages one entity type with entity-named methods (add_<entity>, get_<entity>,
list_<entity>), so a single backend class (e.g. ``SqliteStore``) can implement
all of them, while a future backend can implement them independently.

The core depends on these Protocols, never on SQLite or any concrete store.
"""
from __future__ import annotations

from typing import Protocol, runtime_checkable

from ..evidence.models import Evidence
from ..execution.models import Artifact, ToolRun
from ..findings.models import Finding


@runtime_checkable
class ProjectRepository(Protocol):
    def add_project(self, project_id: str, name: str, metadata: dict | None = None) -> None: ...
    def get_project(self, project_id: str) -> dict | None: ...
    def list_projects(self) -> list[dict]: ...


@runtime_checkable
class TargetRepository(Protocol):
    def add_target(self, target_id: str, project_id: str, kind: str, value: str) -> None: ...
    def get_target(self, target_id: str) -> dict | None: ...
    def list_targets(self) -> list[dict]: ...


@runtime_checkable
class ScanRepository(Protocol):
    def add_scan(self, scan_id: str, project_id: str, target_id: str, status: str) -> None: ...
    def get_scan(self, scan_id: str) -> dict | None: ...
    def list_scans(self) -> list[dict]: ...


@runtime_checkable
class TaskRepository(Protocol):
    def add_task(self, task_id: str, scan_id: str, area: str, description: str) -> None: ...
    def get_task(self, task_id: str) -> dict | None: ...
    def list_tasks(self) -> list[dict]: ...


@runtime_checkable
class AgentRunRepository(Protocol):
    def add_agent_run(self, agent_run_id: str, task_id: str, agent: str) -> None: ...
    def get_agent_run(self, agent_run_id: str) -> dict | None: ...
    def list_agent_runs(self) -> list[dict]: ...


@runtime_checkable
class ToolRunRepository(Protocol):
    def add_tool_run(self, run: ToolRun) -> None: ...
    def get_tool_run(self, tool_run_id: str) -> ToolRun | None: ...
    def list_tool_runs(self) -> list[ToolRun]: ...


@runtime_checkable
class ArtifactRepository(Protocol):
    def add_artifact(self, artifact: Artifact) -> None: ...
    def get_artifact(self, artifact_id: str) -> Artifact | None: ...
    def list_artifacts(self) -> list[Artifact]: ...


@runtime_checkable
class EvidenceRepository(Protocol):
    def add_evidence(self, evidence: Evidence) -> None: ...
    def get_evidence(self, evidence_id: str) -> Evidence | None: ...
    def list_evidence(self) -> list[Evidence]: ...


@runtime_checkable
class FindingRepository(Protocol):
    def add_finding(self, finding: Finding) -> None: ...
    def get_finding(self, finding_id: str) -> Finding | None: ...
    def list_findings(self) -> list[Finding]: ...
